image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - composer install
  - yarn install --force
  - symfony console doctrine:schema:create
  - symfony console doctrine:fixtures:load

stages:
  - build
  - test

Build:
  stage: build
  script:
    - npm run build
      
