image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn install
  - composer require symfony/webpack-encore-bundle
  - composer require symfony/form

stages:
  - build
  - test

Build:
  stage: build
  script:
    - npm run build
      
