image: php:latest

cache:
  paths:
    - vendor/

before_script:
  - com
  - php bin/console doctrine:database:create
  - symfony console make:migration
  - symfony console doctrine:migrations:migrate
  - composer require symfony/form

  test:
    script:
      - npm run-script build
      
